/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as GamesGameIdIndexRouteImport } from './routes/games/$gameId/index'
import { Route as GamesGameIdPlayRouteImport } from './routes/games/$gameId/play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdIndexRoute = GamesGameIdIndexRouteImport.update({
  id: '/games/$gameId/',
  path: '/games/$gameId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdPlayRoute = GamesGameIdPlayRouteImport.update({
  id: '/games/$gameId/play',
  path: '/games/$gameId/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games/': typeof GamesIndexRoute
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/games/$gameId/': typeof GamesGameIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesIndexRoute
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/games/$gameId': typeof GamesGameIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games/': typeof GamesIndexRoute
  '/games/$gameId/play': typeof GamesGameIdPlayRoute
  '/games/$gameId/': typeof GamesGameIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/games/' | '/games/$gameId/play' | '/games/$gameId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/games' | '/games/$gameId/play' | '/games/$gameId'
  id: '__root__' | '/' | '/games/' | '/games/$gameId/play' | '/games/$gameId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  GamesGameIdPlayRoute: typeof GamesGameIdPlayRoute
  GamesGameIdIndexRoute: typeof GamesGameIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/': {
      id: '/games/$gameId/'
      path: '/games/$gameId'
      fullPath: '/games/$gameId/'
      preLoaderRoute: typeof GamesGameIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId/play': {
      id: '/games/$gameId/play'
      path: '/games/$gameId/play'
      fullPath: '/games/$gameId/play'
      preLoaderRoute: typeof GamesGameIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  GamesGameIdPlayRoute: GamesGameIdPlayRoute,
  GamesGameIdIndexRoute: GamesGameIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
